apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: test
    prometheus: test-platform
  name: test
  namespace: test
spec:
  groups:
    - name: test-alerts
      rules:
        - alert: dlq-not-empty
          annotations:
            message: Dead letter queue {{ $labels.queue_name }} has {{ $value }} message(s)
          expr: |-
            sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"test-.*-dlq"} offset 5m) by (queue_name) > 0
          for: 15m
          labels:
            severity: test-notifications
